### PR TITLE
Added Registration page actions 1

### PR DESCRIPTION
**Pull request by Raviteja-Yendamuri**
Hi RavitejaY28041994.

I have added Registration Page code. Please review and approve.

Thanks

### CODE REVIEW

**Comment by RavitejaY28041994** [comment]
Hi Raviteja-Yendamuri,

The code looks good for me.

**Comment by RavitejaY28041994** [comment]
> Hi Raviteja-Yendamuri,
> 
> The code looks good for me.

@Raviteja-Yendamuri

**Comment by RavitejaY28041994** [comment]
Hi @Raviteja-Yendamuri, 

Please proceed with merge.

Thanks

**Comment by Raviteja-Yendamuri** [comment]
Hi @RavitejaY28041994, Merged Please check the code.

**Pull request merged**
